services:
  envoy:
    build: ./envoy
    container_name: envoy
    ports:
      - "9080:9080"   # 外向け API
      - "9901:9901"   # Envoy admin
    depends_on:
      - idp

  idp:
    build: ./idp
    container_name: idp
    ports:
      - "8081:8081"

  micro_service_1:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - "8082:80"  # httpbinのポート

  micro_service_2:
    build: ./micro_service
    container_name: micro_service_2
    ports:
      - "8083:8083"  # マイクロサービスのポート
